#!/usr/bin/env bash
# vault-healthcheck.sh — exbrain の健全性を点検し、ダッシュボードを書き、RED時に通知する。
# SessionStart hook から起動（FDAコンテキスト）。安全な範囲だけ自動修復。
# これが「2ヶ月サイレント故障に気づけなかった」再発を防ぐメタ層。
set +e
VAULT="$HOME/vault"; cd "$VAULT" 2>/dev/null || exit 0
DASH="$VAULT/system/health-dashboard.md"
JSON="$VAULT/system/.health-latest.json"
mkdir -p "$VAULT/system"

reds=0; yellows=0; rows=""
add(){ rows="${rows}| $1 | $2 | $3 |
"; [ "$2" = "🔴" ] && reds=$((reds+1)); [ "$2" = "🟡" ] && yellows=$((yellows+1)); return 0; }

# 直近 pull が走っている前提（SessionStart で --pull-only 実行済み）。ここでは fetch しない＝軽量。
behind=$(git rev-list --count HEAD..origin/main 2>/dev/null || echo 0)
ahead=$(git rev-list --count origin/main..HEAD 2>/dev/null || echo 0)
uu=$(git status -s 2>/dev/null | grep -c '^UU')
dirty=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')

# 競合
[ "${uu:-0}" -gt 0 ] 2>/dev/null && add "マージ競合" "🔴" "${uu}ファイル未解決 → 手動解消が必要"

# クラウド同期
if [ "${behind:-0}" -gt 0 ] 2>/dev/null; then add "クラウド取込" "🟡" "${behind}コミット未取込（次回起動で解消）"; else add "クラウド取込" "🟢" "最新"; fi

# 未push（最古の未pushコミットの経過時間で判定。旧 .last-commit 方式は誤検知バグのため廃止 2026-07-04）
if [ "${ahead:-0}" -gt 0 ] 2>/dev/null; then
  oldest=$(git log --format=%ct origin/main..HEAD 2>/dev/null | tail -1)
  age=$(( ($(date +%s) - ${oldest:-$(date +%s)}) / 3600 ))
  [ "$age" -gt 12 ] 2>/dev/null && add "未pushコミット" "🔴" "${ahead}件・最古${age}h前（push停止の疑い）" || add "未pushコミット" "🟡" "${ahead}件（次回Stopでpush）"
else
  add "push" "🟢" "送信済み"
fi

# 本日の日報
[ -f "daily/$(date +%F).md" ] && add "本日の日報" "🟢" "存在" || add "本日の日報" "🟡" "未生成（朝のクラウド生成待ち）"

# MEMORY 鮮度（クラウド認知が生きているか）
mupd=$(grep -m1 '^updated:' MEMORY.md 2>/dev/null | awk '{print $2}')
if [ -n "$mupd" ] && [ "$mupd" \> "$(date -v-3d +%F 2>/dev/null)" ]; then add "MEMORY鮮度" "🟢" "updated:$mupd"; else add "MEMORY鮮度" "🟡" "updated:${mupd:-?}（クラウド認知の停止疑い）"; fi

# launchd 異常終了ジョブ
fails=$(launchctl list 2>/dev/null | awk '$1!="-" && $2!=0 && /com\.YOURNAME/{print $3"="$2}' | tr '\n' ' ')
[ -n "$fails" ] && add "launchdジョブ異常" "🟡" "$fails" || add "launchdジョブ" "🟢" "正常"

verdict="🟢 all green"
[ $yellows -gt 0 ] && verdict="🟡 ${yellows} warnings"
[ $reds -gt 0 ] && verdict="🔴 ${reds} critical"

# ダッシュボード出力（git追跡＝履歴も残る）
{
  echo "<!-- auto-generated by vault-healthcheck.sh — DO NOT EDIT -->"
  echo "# Vault Health — $(date '+%F %H:%M') — $verdict"
  echo
  echo "| probe | status | detail |"
  echo "|---|---|---|"
  printf "%s" "$rows"
} > "$DASH"
printf '{"ts":"%s","verdict":"%s","reds":%d,"yellows":%d}\n' "$(date '+%F %T')" "$verdict" "$reds" "$yellows" > "$JSON"

# RED時のみ通知（朝夕Slack上限ポリシーに非干渉＝OSローカル通知のみ）
[ $reds -gt 0 ] && osascript -e "display notification \"exbrain健全性: ${reds}件のcritical\" with title \"vault health 🔴\" sound name \"Basso\"" 2>/dev/null

# 安全な自動修復: 競合が無くバックログがあれば commit+push（破壊しない範囲のみ）
if [ "${dirty:-0}" -gt 0 ] && [ "${uu:-0}" -eq 0 ]; then
  ( bash "$VAULT/scripts/vault-sync.sh" --force >/dev/null 2>&1 & )
fi
exit 0
